plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    // Forge Config API Port
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${project.forge_config_api_port_version}"
    modImplementation("maven.modrinth:forge-config-api-port:v${project.forge_config_api_port_version}-${project.minecraft_version}-Fabric") {
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }

    // Development QOL
    modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            getDisplayName().set(("Fabric Client"))
            getGenerateRunConfig().set((true))
            var clientDir = "run/client"
            if (!file(clientDir).exists()) {
                mkdir(clientDir)
            }
            getRunDirectory().set(getProject().file((clientDir)))
        }
        server {
            server()
            getDisplayName().set(("Fabric Server"))
            getGenerateRunConfig().set((true))
            var serverDir = "run/server"
            if (!file(serverDir).exists()) {
                mkdir(serverDir)
            }
            getRunDirectory().set(getProject().file((serverDir)))
        }
    }
}

publishMods {
    displayName = "${mod_id}-fabric-${minecraft_version}-${mod_version}"
    version = "${minecraft_version}-${mod_version}"
    file = tasks.remapJar.archiveFile
    modLoaders.add("fabric")

    curseforge("curseforgeFabric") {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        changelogType = "markdown"
        javaVersions.add(JavaVersion.toVersion(java_version))
        minecraftVersions.addAll(modrinth_gameVersions.split(","))
        projectId = curseforge_id
        client = true
        server = false

        requires("forge-config-api-port")
    }

    modrinth("modrinthFabric") {
        accessToken = System.getenv("MODRINTH_TOKEN")
        minecraftVersions.addAll(modrinth_gameVersions.split(","))
        projectId = modrinth_id

        requires("forge-config-api-port")
    }
}