plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            getDisplayName().set(("Fabric Client"))
            getGenerateRunConfig().set((true))
            var clientDir = "run/client"
            if (!file(clientDir).exists()) {
                mkdir(clientDir)
            }
            getRunDirectory().set(getProject().file((clientDir)))
        }
        server {
            server()
            getDisplayName().set(("Fabric Server"))
            getGenerateRunConfig().set((true))
            var serverDir = "run/server"
            if (!file(serverDir).exists()) {
                mkdir(serverDir)
            }
            getRunDirectory().set(getProject().file((serverDir)))
        }
    }
}