# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
enabled_platforms=fabric,neoforge

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_version=2024.11.17
parchment_minecraft=1.21.1

# Project
license=MIT
credits=IanAnderson
repoURL=https://github.com/IanMods/F3-Backport
issueTrackerURL=https://github.com/IanMods/F3-Backport/issues

# Mod options
mod_version=1.0.0
mod_id=f3backport
mod_group=club.iananderson
mod_name=F3-Backport
mod_author=IanAnderson
mod_description=Backport of 26.4 F3 menu changes

# Minecraft properties
minecraft_version=1.21.1
minecraft_version_range=[1.21, 1.21.2)
java_version=21

# Curseforge/Modrinth
curseforge_id=
curseforge_gameVersions=1.21,1.21.1
modrinth_id=
modrinth_gameVersions=1.21,1.21.1

# Fabric properties
# https://fabricmc.net/develop/
fabric_loader_version=0.19.5
fabric_api_version=0.116.15+1.21.1
fabric_version_range=>=1.21 <=1.21.1

# Neoforge properties
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.1.249
neoforge_version_range=[21.0,)
neoforge_loader_version_range=[4,)

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430

# Mixins
mixin_version=0.8.5
mixin_extras_version=0.5.0

# ForgeConfigApiPort properties
# https://modrinth.com/mod/forge-config-api-port/versions?g=1.21.1&l=fabric
forge_config_api_port_version=21.1.6

# Development QOL
modmenu_version=11.0.4