plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            var clientDir = "run/client"
            if (!file(clientDir).exists()) {
                mkdir(clientDir)
            }
            setGameDirectory(file(clientDir))
        }
        data {
            data()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()

        }
        server {
            server {
                server()
                var serverDir = "run/server"
                if (!file(serverDir).exists()) {
                    mkdir(serverDir)
                }
                setGameDirectory(file(serverDir))
            }
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenCentral()

    exclusiveContent {
        forRepository {
            maven {
                name = "CurseMaven"
                url = uri("https://cursemaven.com")
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth Maven"
                url = uri("https://api.modrinth.com/maven")
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}

publishMods {
    displayName = "${mod_id}-neoforge-${minecraft_version}-${mod_version}"
    version = "${minecraft_version}-${mod_version}"
    file = tasks.jar.archiveFile
    modLoaders.add("neoforge")

    curseforge("curseforgeNeoForge") {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        changelogType = "markdown"
        javaVersions.add(JavaVersion.toVersion(java_version))
        minecraftVersions.addAll(curseforge_gameVersions.split(","))
        projectId = curseforge_id
        client = true
        server = false
    }

    modrinth("modrinthNeoForge") {
        accessToken = System.getenv("MODRINTH_TOKEN")
        minecraftVersions.addAll(modrinth_gameVersions.split(","))
        projectId = modrinth_id
    }
}